"""Alembic environment — async engine, model metadata, autogenerate filters."""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.config import settings
from app.models import Base

config = context.config

# One source of connection truth: settings, not alembic.ini.
url = settings.sqlalchemy_url
if url.startswith("postgresql://"):
    url = url.replace("postgresql://", "postgresql+psycopg://", 1)
config.set_main_option("sqlalchemy.url", url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Child partitions of rider_location_pings are created by DDL in migration 0001,
# not by any model, so autogenerate would propose dropping them on every run.
EXCLUDED_PREFIXES = ("rider_location_pings_",)


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Restrict autogenerate to objects this codebase actually owns.

    The postgis/postgis image enables postgis, postgis_topology AND
    postgis_tiger_geocoder, which together install spatial_ref_sys plus roughly
    thirty tiger tables (`tract`, `zcta5`, `edges`, …) and their sequences.
    Those belong to the extensions. Without this filter every `alembic check`
    reports them as drift and every autogenerated migration proposes dropping
    them — which would break PostGIS.
    """
    schema = getattr(obj, "schema", None)
    if schema not in (None, "public"):
        return False

    if type_ == "table":
        if name.startswith(EXCLUDED_PREFIXES):
            return False
        # A reflected table with no corresponding model is not ours to manage.
        if reflected and name not in target_metadata.tables:
            return False

    # GeoAlchemy2 manages its own spatial indexes; comparing them produces
    # perpetual false drift.
    if type_ == "index" and name and name.startswith("idx_") and "geom" in name:
        return False

    # Functional indexes whose expression Alembic cannot compare. Postgres
    # normalises the stored expression (adding ::regconfig casts, parenthesising
    # the concatenation), so a textual match against the model never succeeds and
    # every run proposes dropping and recreating an identical index.
    #
    # Alembic already skips ix_restaurants_name_trgm on its own because it
    # detects the `gin_trgm_ops` operator clause; the tsvector index has no
    # operator clause, so it needs naming here.
    #
    # TRADE-OFF: real changes to these indexes will NOT be auto-detected. Any
    # edit to them must be hand-written into a migration.
    if type_ == "index" and name in {"ix_menu_items_search"}:
        return False
    return True


def _configure(connection: Connection | None = None, **kw) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
        # Renders enum/array types with their schema so generated migrations
        # are explicit rather than search_path-dependent.
        include_schemas=False,
        **kw,
    )


def run_migrations_offline() -> None:
    _configure(url=config.get_main_option("sqlalchemy.url"), literal_binds=True,
               dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_async_migrations())
